# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zichen (Vincent) Zhang
#email: @
description: > # this means to ignore newlines until "baseurl:"
    Academic blog of Zichen Zhang.
baseurl: "/~zichen2/blog" # the subpath of your site, e.g. /blog
url: "http://webdocs.cs.ualberta.ca" # the base hostname & protocol for your site
twitter_username: vzhangca
github_username:  vincentzhang
linkedin_username:  vincezhang

# Build settings
markdown: kramdown
